# Generated by Django 4.2.1 on 2023-05-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='LQ00000011', max_length=10, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('gender', models.CharField(max_length=10, verbose_name='Gender')),
                ('address', models.TextField(verbose_name='Address')),
                ('image', models.ImageField(blank=True, null=True, upload_to='users/', verbose_name='Profile Image')),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
        ),
    ]
